[/]
color-scheme='prefer-dark'
document-font-name='Sans 12'
font-name='Ubuntu Sans 12'
gtk-theme='Yaru-dark'
icon-theme='Yaru'
monospace-font-name='Ubuntu Sans Mono 14'
text-scaling-factor=0.99999999999999978
