[/]
alphabetize=false
fixed-widths=true
hide-icons=false
hide-zeros=false
icon-style=0
menu-centered=false
position-in-panel=2
show-battery=true
show-fan=true
show-gpu=true
show-memory=true
show-network=true
show-processor=true
show-storage=true
show-system=true
show-temperature=true
show-voltage=true
use-higher-precision=false
