[/]
cli-toggle=false
countdown-timer=10800
duration-timer=2
duration-timer-list=[3600, 10800, 21600]
indicator-position-max=3
show-indicator='only-active'
show-timer=false
use-custom-duration=true
user-enabled=false
